import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';

import './globals.css';

import { ReactNode } from 'react';

import { auth } from '@/auth';
import { Toaster } from '@/components/ui';
import { ThemeProvider } from '@/lib/contexts/theme-context';
import Providers from '@/lib/providers/provider';
import { Theme } from '@/lib/types';
import { cn } from '@/lib/utils';
import { cookies } from 'next/headers';

const inter = Inter({
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/yana-ico.svg',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  const cookieStore = await cookies();
  const cookieTheme = cookieStore.get('theme');
  const theme = cookieTheme ? (cookieTheme.value as Theme) : 'dark';
  return (
    <html lang='en'>
      <body className={cn('antialiased', inter.className)}>
        <Providers session={session}>
          <ThemeProvider defaultTheme={theme}>
            <div className='flex flex-col'>
              {children}
              <Toaster />
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
